image: node:latest

stages:
  - mirror

mirror_to_github:
  stage: mirror
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get update -q && apt-get install -y -q git
    - git config --global user.name "tgorni"
    - git config --global user.email "gornitom@gmail.com"
  script:
    - git remote add github https://$GITHUB_TOKEN@github.com/tgorni/cribthem.git
    - git push -f github main:main
  only:
    - main

pages:
  script:
    - mkdir public
    - echo "<html><body><h1>CribThem Releases</h1>" > public/index.html
    - echo "<a href='https://gitlab.com/tgorni/cribthem/-/archive/v1.1.0/cribthem-v1.1.0.zip'>cribthem-v1.1.0</a>" >> public/index.html
    - echo "<a href='https://gitlab.com/tgorni/cribthem/-/archive/v1.1.0/cribthem-v1.0.0.zip'>cribthem-v1.0.0</a>" >> public/index.html
    - echo "<a href='https://gitlab.com/tgorni/cribthem/-/archive/v1.1.0/cribthem-v0.0.1.zip'>cribthem-v0.0.1</a>" >> public/index.html
    - echo "</body></html>" >> public/index.html
  artifacts:
    paths:
      - public
  only:
    - main
